version: '3.8'
services:
  api-orders-luizalabs:
    image: node:22
    container_name: api-orders-luizalabs
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
